### PR TITLE
Added support for lead score updating

### PR DESCRIPTION
**Pull request by Clopy**
Hi, I was evaluating agileCRM and stumbled upon your python bindings. We needed support for updating the lead_score so I decided to add it and send it back. Thanks for all your work! Let me know if everything is ok.

### CODE REVIEW

**Comment by vpetersson** [comment]
Thanks, @Clopy. I'm a bit torn here what would be the better way. There are two ways to look at this: 
- Overwrite the score
- Adjust to the score

I'm inclined towards the latter, such that you can pass in a positive or negative value to balance the score. However, it appears as this code does the former.

**Comment by Clopy** [comment]
Hi @vpetersson Yes, the code does overwrite the score. I tried following the rest-api style to be consistent. There are two different calls there, one that updates the contact (and overwrites the score if it is passed as a parameter) and one that adds/subtracts from the score. Since I used the update_contact function I figured the correct way was to overwrite. Maybe we could add an add_score function like in the rest-api with the functionality your propose. 

https://github.com/agilecrm/rest-api

You can see the add score call at 1.9.

Let me know what you think and I'll create another PR fixing your other comment too. Thanks!

**Comment by vpetersson** [comment]
Ah yes, I see what you mean. Ok, with that in mind, let's just address the comment I had in the PR (just update the existing one). 

We can then add another function named `adjust_score()` similar to `add_tag()` that does the following: 
- Fetch the user object by UUID or email
- Reads in the existing score
- Adjust the score accordingly
- Push the new object with the new score

What do you think?

**Comment by Clopy** [comment]
I don't think we need to do all of that, we can use the add-score api call:

https://github.com/agilecrm/rest-api#110-add-score-to-a-contact-using-email-id

It increases/decreases the score automatically, so we only need one call. I'll probably be working on the tasks api a bit too the next days, so I'll fix this request and possibly open another one for the tasks api.

**Comment by vpetersson** [comment]
Good find. Yeah, that would be nice to get in. We don't use the task feature server-side, but it would be nice to have in the library.

**Pull request merged**
